export const FEATURES = {
  GEM_OPTIMIZATION: true,
  ENCHANT_OPTIMIZATION: true,
  TIER_SET_FILTERING: true,
  ITEM_UPGRADE_CURRENCY: true,
  CATALYST_CHARGES: true,
  EMBELLISHMENT_COMPARISON: false,
  TALENT_COMPARISON: false,
} as const;
